using FluxBrowser.Models;
using FluxBrowser.Services;
using Microsoft.Web.WebView2.Core;
using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Threading;
namespace FluxBrowser;
public partial class MainWindow : Window
{
 readonly ObservableCollection<BrowserTab> tabs=new(); readonly BrowserStore store=new(); readonly List<HistoryItem> history; readonly List<BookmarkItem> bookmarks; FluxSettings settings; BrowserTab? active;
 public MainWindow(){InitializeComponent();history=store.Load<HistoryItem>(store.HistoryFile);bookmarks=store.Load<BookmarkItem>(store.BookmarksFile);settings=store.LoadObject(store.SettingsFile,new FluxSettings()); Loaded+=async(_,__)=>{await AddTab(true); var timer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(1)};timer.Tick+=(_,__)=>Clock.Text=DateTime.Now.ToString("dddd, d MMMM  •  HH:mm");timer.Start();ApplySettings();};}
 async Task AddTab(bool home=false,bool isPrivate=false){var tab=new BrowserTab{IsPrivate=isPrivate};tabs.Add(tab);active=tab;await tab.View.EnsureCoreWebView2Async();tab.View.CoreWebView2.Settings.AreDevToolsEnabled=true;tab.View.CoreWebView2.Settings.AreDefaultContextMenusEnabled=true;tab.View.CoreWebView2.DocumentTitleChanged+=(_,__)=>Dispatcher.Invoke(()=>{tab.Title=tab.View.CoreWebView2.DocumentTitle;if(tab==active)RenderTabs();});tab.View.CoreWebView2.SourceChanged+=(_,__)=>Dispatcher.Invoke(()=>{tab.Url=tab.View.Source?.ToString()??"";if(tab==active)AddressBar.Text=tab.Url;});tab.View.CoreWebView2.NavigationCompleted+=(_,__)=>Dispatcher.Invoke(()=>{if(!tab.IsPrivate&&tab.View.Source!=null){history.Insert(0,new(tab.Title,tab.View.Source.ToString(),DateTime.Now));if(history.Count>1000)history.RemoveRange(1000,history.Count-1000);store.Save(store.HistoryFile,history);}StatusText.Text="Done";});ShowTab(tab);if(home)ShowNewTab();RenderTabs();}
 void RenderTabs(){TabsPanel.Children.Clear();foreach(var t in tabs){var panel=new StackPanel{Orientation=Orientation.Horizontal};var b=new Button{Content=t.Title.Length>20?t.Title[..20]+"…":t.Title,Tag=t,MinWidth=130,MaxWidth=210,Background=t==active?new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(38,40,50)):System.Windows.Media.Brushes.Transparent};b.Click+=(_,__)=>ShowTab((BrowserTab)b.Tag);var x=new Button{Content="×",Tag=t,Padding=new Thickness(6)};x.Click+=CloseTab_Click;panel.Children.Add(b);panel.Children.Add(x);TabsPanel.Children.Add(panel);}}
 void ShowTab(BrowserTab tab){active=tab;BrowserHost.Children.Clear();BrowserHost.Children.Add(tab.View);NewTab.Visibility=tab.Url=="flux://newtab"?Visibility.Visible:Visibility.Collapsed;tab.View.Visibility=NewTab.Visibility==Visibility.Visible?Visibility.Collapsed:Visibility.Visible;AddressBar.Text=tab.Url=="flux://newtab"?"":tab.Url;RenderTabs();}
 void ShowNewTab(){if(active==null)return;active.Url="flux://newtab";active.Title="New Tab";ShowTab(active);}
 string SearchUrl(string q)=>settings.SearchEngine switch{"Bing"=>"https://www.bing.com/search?q="+Uri.EscapeDataString(q),"DuckDuckGo"=>"https://duckduckgo.com/?q="+Uri.EscapeDataString(q),_=>"https://www.google.com/search?q="+Uri.EscapeDataString(q)};
 void Navigate(string input){if(active==null||string.IsNullOrWhiteSpace(input))return;var v=input.Trim();if(v=="flux://newtab"){ShowNewTab();return;}if(v.Contains(' ')||!v.Contains('.'))v=SearchUrl(v);else if(!v.StartsWith("http://")&&!v.StartsWith("https://")&&!v.StartsWith("file://"))v="https://"+v;NewTab.Visibility=Visibility.Collapsed;active.View.Visibility=Visibility.Visible;active.View.Source=new Uri(v);StatusText.Text="Loading…";}
 void ApplySettings(){Clock.Visibility=settings.ShowClock?Visibility.Visible:Visibility.Collapsed;Greeting.Visibility=settings.ShowGreeting?Visibility.Visible:Visibility.Collapsed;QuickLinks.Visibility=settings.ShowQuickLinks?Visibility.Visible:Visibility.Collapsed;}
 void AddressBar_KeyDown(object s,KeyEventArgs e){if(e.Key==Key.Enter)Navigate(AddressBar.Text);} void NewTabSearch_KeyDown(object s,KeyEventArgs e){if(e.Key==Key.Enter)Navigate(NewTabSearch.Text);} void NewTabSearch_GotFocus(object s,RoutedEventArgs e){if(NewTabSearch.Text=="Search the web")NewTabSearch.Clear();}
 void Back_Click(object s,RoutedEventArgs e){if(active?.View.CanGoBack==true)active.View.GoBack();} void Forward_Click(object s,RoutedEventArgs e){if(active?.View.CanGoForward==true)active.View.GoForward();} void Reload_Click(object s,RoutedEventArgs e){active?.View.Reload();} void Home_Click(object s,RoutedEventArgs e)=>ShowNewTab(); async void NewTab_Click(object s,RoutedEventArgs e)=>await AddTab(true);
 void Bookmark_Click(object s,RoutedEventArgs e){if(active?.View.Source==null)return;var url=active.View.Source.ToString();if(!bookmarks.Any(x=>x.Url==url)){bookmarks.Insert(0,new(active.Title,url));store.Save(store.BookmarksFile,bookmarks);StatusText.Text="Bookmarked";}}
 async void Menu_Click(object s,RoutedEventArgs e){var menu=new ContextMenu();void item(string name,RoutedEventHandler click){var i=new MenuItem{Header=name};i.Click+=click;menu.Items.Add(i);}item("New tab",async(_,__)=>await AddTab(true));item("New private window",(_,__)=>{var w=new MainWindow();w.Title="Flux Private";w.Show();});item($"Bookmarks ({bookmarks.Count})",(_,__)=>MessageBox.Show(string.Join("\n",bookmarks.Take(20).Select(x=>$"★ {x.Title}\n{x.Url}")),"Flux Bookmarks"));item($"History ({history.Count})",(_,__)=>MessageBox.Show(string.Join("\n",history.Take(20).Select(x=>$"{x.VisitedAt:g}  {x.Title}\n{x.Url}")),"Flux History"));item("Search: Google",(_,__)=>SetSearch("Google"));item("Search: Bing",(_,__)=>SetSearch("Bing"));item("Search: DuckDuckGo",(_,__)=>SetSearch("DuckDuckGo"));item("Toggle clock",(_,__)=>{settings.ShowClock=!settings.ShowClock;SaveSettings();});item("Toggle greeting",(_,__)=>{settings.ShowGreeting=!settings.ShowGreeting;SaveSettings();});item("Toggle quick links",(_,__)=>{settings.ShowQuickLinks=!settings.ShowQuickLinks;SaveSettings();});item("Developer tools",(_,__)=>active?.View.CoreWebView2?.OpenDevToolsWindow());menu.IsOpen=true;await Task.CompletedTask;}
 void SetSearch(string s){settings.SearchEngine=s;SaveSettings();}void SaveSettings(){store.SaveObject(store.SettingsFile,settings);ApplySettings();StatusText.Text="Settings saved";}
 void QuickLink_Click(object s,RoutedEventArgs e){if(s is Button b&&b.Tag is string u)Navigate(u);} void CloseTab_Click(object s,RoutedEventArgs e){if(s is not Button b||b.Tag is not BrowserTab t)return;t.View.Dispose();tabs.Remove(t);if(tabs.Count==0){Close();return;}ShowTab(tabs[Math.Max(0,tabs.Count-1)]);}
 void TitleBar_MouseLeftButtonDown(object s,MouseButtonEventArgs e){if(e.ClickCount==2)Max_Click(s,e);else if(e.ButtonState==MouseButtonState.Pressed)DragMove();}void Min_Click(object s,RoutedEventArgs e)=>WindowState=WindowState.Minimized;void Max_Click(object s,RoutedEventArgs e)=>WindowState=WindowState==WindowState.Maximized?WindowState.Normal:WindowState.Maximized;void Close_Click(object s,RoutedEventArgs e)=>Close();
}
