using FluxBrowser.Models;
using FluxBrowser.Services;
using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Threading;
namespace FluxBrowser;
public partial class MainWindow : Window
{
 readonly ObservableCollection<BrowserTab> tabs=new(); readonly BrowserStore store=new(); readonly List<HistoryItem> history; readonly List<BookmarkItem> bookmarks; FluxSettings settings; BrowserTab? active;
 public MainWindow(){InitializeComponent();history=store.Load<HistoryItem>(store.HistoryFile);bookmarks=store.Load<BookmarkItem>(store.BookmarksFile);settings=store.LoadObject(store.SettingsFile,new FluxSettings());Loaded+=async(_,__)=>{await AddTab(true);var timer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(1)};timer.Tick+=(_,__)=>Clock.Text=DateTime.Now.ToString("dddd, d MMMM  •  HH:mm");timer.Start();ApplySettings();};}
 async Task AddTab(bool home=false,bool isPrivate=false){var tab=new BrowserTab{IsPrivate=isPrivate};tabs.Add(tab);active=tab;await tab.View.EnsureCoreWebView2Async();tab.View.CoreWebView2.Settings.AreDevToolsEnabled=true;tab.View.CoreWebView2.DocumentTitleChanged+=(_,__)=>Dispatcher.Invoke(()=>{tab.Title=tab.View.CoreWebView2.DocumentTitle;if(tab==active)RenderTabs();});tab.View.CoreWebView2.SourceChanged+=(_,__)=>Dispatcher.Invoke(()=>{tab.Url=tab.View.Source?.ToString()??"";if(tab==active)AddressBar.Text=tab.Url;});tab.View.CoreWebView2.NavigationCompleted+=(_,__)=>Dispatcher.Invoke(()=>{if(!tab.IsPrivate&&tab.View.Source!=null){history.Insert(0,new(tab.Title,tab.View.Source.ToString(),DateTime.Now));if(history.Count>1000)history.RemoveRange(1000,history.Count-1000);store.Save(store.HistoryFile,history);}});ShowTab(tab);if(home)ShowNewTab();RenderTabs();}
 Button MakeButton(string text,object? tag=null){var b=new Button{Content=text,Tag=tag,Foreground=Brushes.White,Background=new SolidColorBrush(Color.FromRgb(24,24,34)),BorderThickness=new Thickness(0),Padding=new Thickness(14),Margin=new Thickness(0,4,0,4),HorizontalContentAlignment=HorizontalAlignment.Left,Cursor=Cursors.Hand};return b;}
 void RenderTabs(){TabsPanel.Children.Clear();foreach(var t in tabs){var p=new Border{CornerRadius=new CornerRadius(9,9,0,0),Background=t==active?new SolidColorBrush(Color.FromRgb(31,20,29)):new SolidColorBrush(Color.FromRgb(15,15,23)),Margin=new Thickness(2,1,2,0),BorderBrush=t==active?new SolidColorBrush(Color.FromRgb(255,23,79)):Brushes.Transparent,BorderThickness=new Thickness(0,1,0,0)};var row=new StackPanel{Orientation=Orientation.Horizontal};var b=new Button{Content=t.Title.Length>22?t.Title[..22]+"…":t.Title,Tag=t,Foreground=Brushes.White,Background=Brushes.Transparent,BorderThickness=new Thickness(0),Padding=new Thickness(14,8,8,8),MinWidth=125};b.Click+=(_,__)=>ShowTab((BrowserTab)b.Tag);var x=new Button{Content="×",Tag=t,Foreground=new SolidColorBrush(Color.FromRgb(150,150,165)),Background=Brushes.Transparent,BorderThickness=new Thickness(0),Padding=new Thickness(8)};x.Click+=CloseTab_Click;row.Children.Add(b);row.Children.Add(x);p.Child=row;TabsPanel.Children.Add(p);}}
 void ShowTab(BrowserTab tab){active=tab;BrowserHost.Children.Clear();BrowserHost.Children.Add(tab.View);NewTab.Visibility=tab.Url=="flux://newtab"?Visibility.Visible:Visibility.Collapsed;tab.View.Visibility=NewTab.Visibility==Visibility.Visible?Visibility.Collapsed:Visibility.Visible;AddressBar.Text=tab.Url=="flux://newtab"?"":tab.Url;ClosePanel();RenderTabs();}
 void ShowNewTab(){if(active==null)return;active.Url="flux://newtab";active.Title="New Tab";ShowTab(active);}
 string SearchUrl(string q)=>settings.SearchEngine switch{"Bing"=>"https://www.bing.com/search?q="+Uri.EscapeDataString(q),"DuckDuckGo"=>"https://duckduckgo.com/?q="+Uri.EscapeDataString(q),_=>"https://www.google.com/search?q="+Uri.EscapeDataString(q)};
 void Navigate(string input){if(active==null||string.IsNullOrWhiteSpace(input))return;var v=input.Trim();if(v.Contains(' ')||!v.Contains('.'))v=SearchUrl(v);else if(!v.StartsWith("http://")&&!v.StartsWith("https://")&&!v.StartsWith("file://"))v="https://"+v;NewTab.Visibility=Visibility.Collapsed;active.View.Visibility=Visibility.Visible;active.View.Source=new Uri(v);ClosePanel();}
 void OpenPanel(string title){PanelTitle.Text=title;PanelContent.Children.Clear();SidePanel.Visibility=Visibility.Visible;} void ClosePanel()=>SidePanel.Visibility=Visibility.Collapsed; void ClosePanel_Click(object s,RoutedEventArgs e)=>ClosePanel();
 void BookmarksPanel_Click(object s,RoutedEventArgs e){OpenPanel("Bookmarks");if(bookmarks.Count==0)PanelContent.Children.Add(new TextBlock{Text="No bookmarks yet.",Foreground=Brushes.Gray});foreach(var x in bookmarks){var b=MakeButton("★  "+x.Title+"\n     "+x.Url,x.Url);b.Click+=PanelNavigate;PanelContent.Children.Add(b);}}
 void HistoryPanel_Click(object s,RoutedEventArgs e){OpenPanel("History");if(history.Count==0)PanelContent.Children.Add(new TextBlock{Text="No history yet.",Foreground=Brushes.Gray});foreach(var x in history.Take(80)){var b=MakeButton(x.VisitedAt.ToString("HH:mm")+"   "+x.Title,x.Url);b.Click+=PanelNavigate;PanelContent.Children.Add(b);}}
 void DownloadsPanel_Click(object s,RoutedEventArgs e){OpenPanel("Downloads");PanelContent.Children.Add(new TextBlock{Text="Downloads will appear here. WebView2 download management is next in Flux V1.",TextWrapping=TextWrapping.Wrap,Foreground=new SolidColorBrush(Color.FromRgb(160,160,175)),FontSize=14});}
 void GamingPanel_Click(object s,RoutedEventArgs e){OpenPanel("Flux Gaming");PanelContent.Children.Add(new TextBlock{Text="Gaming Hub",Foreground=Brushes.White,FontSize=24,FontWeight=FontWeights.Bold,Margin=new Thickness(0,0,0,12)});foreach(var q in new[]{("YouTube Gaming","https://youtube.com/gaming"),("Twitch","https://twitch.tv"),("Roblox","https://roblox.com"),("Minecraft","https://minecraft.net")}){var b=MakeButton("🎮  "+q.Item1,q.Item2);b.Click+=PanelNavigate;PanelContent.Children.Add(b);}}
 void SettingsPanel_Click(object s,RoutedEventArgs e){OpenPanel("Customize Flux");PanelContent.Children.Add(new TextBlock{Text="NEW TAB",Foreground=new SolidColorBrush(Color.FromRgb(255,23,79)),FontWeight=FontWeights.Bold,Margin=new Thickness(0,4,0,8)});AddToggle("Show clock",settings.ShowClock,v=>settings.ShowClock=v);AddToggle("Show Flux slogan",settings.ShowGreeting,v=>settings.ShowGreeting=v);AddToggle("Show quick links",settings.ShowQuickLinks,v=>settings.ShowQuickLinks=v);PanelContent.Children.Add(new TextBlock{Text="SEARCH ENGINE",Foreground=new SolidColorBrush(Color.FromRgb(255,23,79)),FontWeight=FontWeights.Bold,Margin=new Thickness(0,20,0,8)});foreach(var engine in new[]{"Google","Bing","DuckDuckGo"}){var b=MakeButton((settings.SearchEngine==engine?"●  ":"○  ")+engine,engine);b.Click+=(a,_)=>{settings.SearchEngine=(string)((Button)a).Tag;SaveSettings();SettingsPanel_Click(a,new RoutedEventArgs());};PanelContent.Children.Add(b);}}
 void AddToggle(string text,bool value,Action<bool> setter){var c=new CheckBox{Content=text,IsChecked=value,Foreground=Brushes.White,FontSize=14,Margin=new Thickness(3,8)};c.Click+=(_,__)=>{setter(c.IsChecked==true);SaveSettings();};PanelContent.Children.Add(c);}
 void Menu_Click(object s,RoutedEventArgs e){OpenPanel("Flux Menu");var nt=MakeButton("＋  New tab");nt.Click+=async(_,__)=>await AddTab(true);PanelContent.Children.Add(nt);var pv=MakeButton("◈  New private tab");pv.Click+=async(_,__)=>await AddTab(true,true);PanelContent.Children.Add(pv);var set=MakeButton("⚙  Customize Flux");set.Click+=SettingsPanel_Click;PanelContent.Children.Add(set);var dev=MakeButton("⌘  Developer tools");dev.Click+=(_,__)=>active?.View.CoreWebView2?.OpenDevToolsWindow();PanelContent.Children.Add(dev);}
 void PanelNavigate(object s,RoutedEventArgs e){if(s is Button b&&b.Tag is string u)Navigate(u);} void ApplySettings(){Clock.Visibility=settings.ShowClock?Visibility.Visible:Visibility.Collapsed;Greeting.Visibility=settings.ShowGreeting?Visibility.Visible:Visibility.Collapsed;QuickLinks.Visibility=settings.ShowQuickLinks?Visibility.Visible:Visibility.Collapsed;} void SaveSettings(){store.SaveObject(store.SettingsFile,settings);ApplySettings();}
 void AddressBar_KeyDown(object s,KeyEventArgs e){if(e.Key==Key.Enter)Navigate(AddressBar.Text);}void NewTabSearch_KeyDown(object s,KeyEventArgs e){if(e.Key==Key.Enter)Navigate(NewTabSearch.Text);}void NewTabSearch_GotFocus(object s,RoutedEventArgs e){if(NewTabSearch.Text.StartsWith("Search"))NewTabSearch.Clear();}void Back_Click(object s,RoutedEventArgs e){if(active?.View.CanGoBack==true)active.View.GoBack();}void Forward_Click(object s,RoutedEventArgs e){if(active?.View.CanGoForward==true)active.View.GoForward();}void Reload_Click(object s,RoutedEventArgs e)=>active?.View.Reload();void Home_Click(object s,RoutedEventArgs e)=>ShowNewTab();async void NewTab_Click(object s,RoutedEventArgs e)=>await AddTab(true);
 void Bookmark_Click(object s,RoutedEventArgs e){if(active?.View.Source==null)return;var url=active.View.Source.ToString();if(!bookmarks.Any(x=>x.Url==url)){bookmarks.Insert(0,new(active.Title,url));store.Save(store.BookmarksFile,bookmarks);}}void QuickLink_Click(object s,RoutedEventArgs e){if(s is Button b&&b.Tag is string u)Navigate(u);}void CloseTab_Click(object s,RoutedEventArgs e){if(s is not Button b||b.Tag is not BrowserTab t)return;t.View.Dispose();tabs.Remove(t);if(tabs.Count==0){Close();return;}ShowTab(tabs[^1]);}
 void TitleBar_MouseLeftButtonDown(object s,MouseButtonEventArgs e){if(e.OriginalSource is Button)return;if(e.ClickCount==2)Max_Click(s,e);else if(e.ButtonState==MouseButtonState.Pressed)DragMove();}void Min_Click(object s,RoutedEventArgs e)=>WindowState=WindowState.Minimized;void Max_Click(object s,RoutedEventArgs e)=>WindowState=WindowState==WindowState.Maximized?WindowState.Normal:WindowState.Maximized;void Close_Click(object s,RoutedEventArgs e)=>Close();
}